# run: docker-compose up
version: "3"
services:
  webapp:
    container_name: pcex-authoring__webapp
    build:
      context: ./pcex-authoring/editor-services/
      dockerfile: ./Dockerfile
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    volumes:
      - ./pcex-authoring-storage:/pcex-authoring/storage
    restart: always
    depends_on:
      - mongodb
  mongodb:
    container_name: pcex-authoring__mongodb
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./pcex-authoring-storage:/bitnami/mongodb
