#!/usr/bin/env python3
"""
backfill_sources.py

Creates a clean, isolated copy of all 123 sources in 'backfilled_sources/':
1. Starts from the validated server backup in 'backups/2026-09-01/sources/'
2. Removes all human-only distractors (present in matched_sources and not generated by LLM)
3. For the 90 sources that already have 3 reviewed LLM distractors: keeps them untouched (3 distractors each)
4. For the 33 sources that have < 3 LLM distractors: backfills all available non-duplicate LLM distractors from 'augmented_sources/'
5. Prepends '[backfilled] ' to the description of all backfilled distractors so human experts can review and select the best 3
"""

import os
import sys
import json
import glob
import argparse
from collections import Counter

def norm(s):
    if not s:
        return ""
    return " ".join(s.strip().split())

def main():
    parser = argparse.ArgumentParser(description="Filter human distractors and backfill all available LLM distractors for the 33 deficit sources.")
    parser.add_argument("--backup-date", default="2026-09-01", help="Date directory of server backup (default: 2026-09-01)")
    parser.add_argument("--output-dir", default=None, help="Custom output directory (default: backfilled_sources/)")
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    backup_sources_dir = os.path.join(script_dir, "backups", args.backup_date, "sources")
    matched_sources_dir = os.path.join(script_dir, "matched_sources")
    augmented_sources_dir = os.path.join(script_dir, "augmented_sources")
    cache_file = os.path.join(script_dir, "genai_cache.json")
    
    if args.output_dir:
        output_dir = os.path.abspath(args.output_dir)
    else:
        output_dir = os.path.join(script_dir, "backfilled_sources")

    os.makedirs(output_dir, exist_ok=True)

    cache = {}
    if os.path.exists(cache_file):
        try:
            with open(cache_file, "r", encoding="utf-8") as f:
                cache = json.load(f).get("distractors", {})
        except Exception:
            cache = {}

    backup_files = sorted(glob.glob(os.path.join(backup_sources_dir, "*.json")))
    print(f"Found {len(backup_files)} backup source files.")
    print(f"Output directory: {output_dir}\n")

    total_sources = len(backup_files)
    total_human_removed = 0
    total_reviewed_kept = 0
    total_backfilled = 0
    sources_backfilled_count = 0
    sources_untouched_count = 0

    backfill_log = []

    for b_path in backup_files:
        sid = os.path.splitext(os.path.basename(b_path))[0]
        m_path = os.path.join(matched_sources_dir, f"{sid}.json")
        a_path = os.path.join(augmented_sources_dir, f"{sid}.json")

        with open(b_path, "r", encoding="utf-8") as bf:
            source = json.load(bf)

        m_data = json.load(open(m_path, "r", encoding="utf-8")) if os.path.exists(m_path) else {}
        a_data = json.load(open(a_path, "r", encoding="utf-8")) if os.path.exists(a_path) else {}

        # 1. Identify legacy human distractor codes
        m_codes = set(norm((d.get("line") or {}).get("content", "")) for d in m_data.get("distractors", []))

        # 2. Collect all LLM generated distractor codes and details from augmented_sources & cache
        lang = source.get("language", "PYTHON")
        stmt = source.get("description", "")
        sol = source.get("code", "")
        lines = source.get("lines", {})
        blank_lines = [int(ln) for ln, info in lines.items() if info.get("blank")]

        cached_llm_codes = set()
        for bl in blank_lines:
            k = f"{lang}::{bl}::{sol}::{stmt}"
            if k in cache:
                for gd in cache[k]:
                    c = norm(gd.get("distractor", ""))
                    if c:
                        cached_llm_codes.add(c)

        # Distractors pool from augmented_sources
        aug_dist_pool = []
        for d in a_data.get("distractors", []):
            code = norm((d.get("line") or {}).get("content", "") if "line" in d else d.get("code", ""))
            raw_comms = (d.get("line") or {}).get("commentList", []) if "line" in d else []
            help_list = d.get("helpList", [])
            desc = (raw_comms[0] if raw_comms and raw_comms[0].strip() else "") or (help_list[0] if help_list and help_list[0].strip() else "") or d.get("description", "")
            ln_num = (d.get("line") or {}).get("number", 0) if "line" in d else d.get("line_number", 0)

            is_llm = (code not in m_codes) or (code in cached_llm_codes)
            if is_llm and code:
                cached_llm_codes.add(code)
                aug_dist_pool.append({
                    "code": (d.get("line") or {}).get("content", "") if "line" in d else d.get("code", ""),
                    "norm_code": code,
                    "description": desc.strip(),
                    "line_number": ln_num
                })

        # 3. Filter current server distractors
        server_distractors = source.get("distractors", [])
        kept_llm_distractors = []
        removed_human_distractors = []
        kept_norm_codes = set()

        for d in server_distractors:
            code = norm(d.get("code", "") if "code" in d else (d.get("line") or {}).get("content", ""))
            if code in m_codes and code not in cached_llm_codes:
                removed_human_distractors.append(d)
                total_human_removed += 1
            else:
                kept_llm_distractors.append(d)
                kept_norm_codes.add(code)
                total_reviewed_kept += 1

        # 4. Backfill ONLY for the 33 sources that have < 3 LLM distractors
        backfilled_for_this_source = 0
        if len(kept_llm_distractors) < 3:
            candidate_pool = [c for c in aug_dist_pool if c["norm_code"] not in kept_norm_codes]

            # Deduplicate candidate pool by norm_code
            seen_cand = set()
            for cand in candidate_pool:
                if cand["norm_code"] not in seen_cand:
                    seen_cand.add(cand["norm_code"])
                    orig_desc = cand["description"]
                    backfill_desc = f"[backfilled] {orig_desc}" if orig_desc else "[backfilled]"

                    new_d = {
                        "code": cand["code"],
                        "description": backfill_desc,
                        "line_number": cand["line_number"]
                    }
                    kept_llm_distractors.append(new_d)
                    kept_norm_codes.add(cand["norm_code"])
                    backfilled_for_this_source += 1
                    total_backfilled += 1

            sources_backfilled_count += 1
            backfill_log.append((sid, source.get("name", ""), backfilled_for_this_source, len(removed_human_distractors), len(kept_llm_distractors)))
        else:
            sources_untouched_count += 1

        # Update source distractors
        source["distractors"] = kept_llm_distractors

        # Save to backfilled_sources/
        out_file = os.path.join(output_dir, f"{sid}.json")
        with open(out_file, "w", encoding="utf-8") as out_f:
            json.dump(source, out_f, indent=2)

    print("=" * 80)
    print("TARGETED LLM DISTRACTORS BACKFILL COMPLETE!")
    print("=" * 80)
    print(f"Total Sources Processed:               {total_sources}")
    print(f"Human-Only Distractors Removed:        {total_human_removed}")
    print(f"Reviewed LLM Distractors Preserved:    {total_reviewed_kept}")
    print(f"Extra LLM Distractors Backfilled:      {total_backfilled}")
    print(f"Sources Untouched (Already 3):         {sources_untouched_count} / {total_sources}")
    print(f"Sources Backfilled (Deficit Sources):  {sources_backfilled_count} / {total_sources}")
    print(f"Output Directory:                      {output_dir}")
    print("=" * 80)

if __name__ == "__main__":
    main()
